# Generated by Django 5.1.6 on 2025-03-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_address_remove_client_last_name_client_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='responsible',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable'),
        ),
    ]
