# Generated by Django 5.1.6 on 2025-03-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_client_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='colony',
            field=models.CharField(default='Gaviotas', max_length=100, verbose_name='Colonia'),
            preserve_default=False,
        ),
    ]
