# Generated by Django 5.1.6 on 2025-03-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.IntegerField(choices=[(0, 'Creado'), (1, 'Activo'), (2, 'Finalizado')], default=0),
        ),
    ]
