# Generated by Django 5.1.6 on 2025-03-05 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_is_active'),
        ('service', '0002_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='asigment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.IntegerField(choices=[(0, 'Creado'), (1, 'Confirmado'), (2, 'Finalizado'), (3, 'Asignado')], default=0),
        ),
    ]
