# Generated by Django 5.1.6 on 2025-03-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_asigment_date_service_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='asigment_date',
            new_name='assigment_date',
        ),
    ]
