# Generated by Django 5.1.6 on 2025-10-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_asigment_date_service_assigment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='summary',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.IntegerField(choices=[(0, 'Creado'), (1, 'Confirmado'), (2, 'Finalizado'), (3, 'Asignado'), (4, 'Reasignado')], default=0),
        ),
    ]
