# Generated by Django 5.1.6 on 2025-10-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_serviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
