# Generated by Django 5.1.6 on 2025-10-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_service_service_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
