# Generated by Django 5.1.6 on 2025-10-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_service_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='request_methods',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
