# Generated by Django 5.1.6 on 2026-04-28 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_userprofile'),
        ('service', '0009_service_request_methods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AddField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('organization', 'service_number')},
        ),
    ]
